env:
  dbHost:    postgres
  dbPort:    "5432"
  dbName:    sticky_dev
  dbUser:    postgres
  dbPass:    postgres
  jwtSecret: very_secret_jwt

image:
  repository: sticky-notes
  tag:        latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

autoscaling:
  enabled: false

service:
  type: ClusterIP
  port: 3000
